MenuItem:
  extensions:
    - Guttmann\SilverStripe\MenuItemExtension
MenuSet:
  extensions:
    - Guttmann\SilverStripe\MenuSetExtension
MenuAdmin:
  extensions:
    - SubsiteMenuExtension
    - Guttmann\SilverStripe\MenuAdminExtension
